package:
  name: obscurecove
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/pythonflaskserverapps/obscurecove.git

requirements:
  build:
    - python
    - setuptools
  run:
    

test:
  imports:
    - obscurecove

about:
  home: https://github.com/pythonflaskserverapps/obscurecove
  license: MIT
  license_file: LICENSE
